import requests

# ksqlDB server URL
KSQLDB_SERVER_URL = "http://localhost:8088"

# ksqlDB query to create the mentions_stream_2 stream
create_mentions_stream_query = """
CREATE STREAM joined_alert_data_stream AS
SELECT
    a.BRANDID AS a_BRANDID,
    a.BRANDNAME AS a_BRANDNAME,
    a.CATEGORYGROUPID AS a_CATEGORYGROUPID,
    a.CATEGORYID AS a_CATEGORYID,
    a.CATEGORYNAME AS a_CATEGORYNAME,
    a.CHANNELTYPE AS a_CHANNELTYPE,
    a.CHANNELGROUPID AS a_CHANNELGROUPID,
    a.DESCRIPTION AS a_DESCRIPTION,
    a.SOCIALID AS a_SOCIALID,
    a.OBJECTID AS a_OBJECTID,
    a.NUMLIKESCOUNT AS a_NUMLIKESCOUNT,
    a.NUMCOMMENTS AS a_NUMCOMMENTS,
    a.NUMCOMMENTSCOUNT AS a_NUMCOMMENTSCOUNT,
    a.NUMSHARECOUNT AS a_NUMSHARECOUNT,
    a.NUMVIDEOVIEWS AS a_NUMVIDEOVIEWS,
    a.SHARECOUNT AS a_SHARECOUNT,
    a.CREATEDDATE AS a_CREATEDDATE,
    a.SENTIMENTTYPE AS a_SENTIMENTTYPE,
    a.PASSIVEPOSITIVESENTIMENTCOUNT AS a_PASSIVEPOSITIVESENTIMENTCOUNT,
    a.NEGATIVESENTIMENTCOUNT AS a_NEGATIVESENTIMENTCOUNT,
    a.NEUTRALSENTIMENTCOUNT AS a_NEUTRALSENTIMENTCOUNT,
    a.TAGID AS a_TAGID,
    a.UPPERCATEGORYID AS a_UPPERCATEGORYID,
    a.ISDELETED AS a_ISDELETED,
    a.SIMPLIFIEDTEXT AS a_SIMPLIFIEDTEXT,
    a.RATING AS a_RATING,
    a.ISVERIFIED AS a_ISVERIFIED,
    a.RETWEETEDSTATUSID AS a_RETWEETEDSTATUSID,
    a.INREPLYTOSTATUSID AS a_INREPLYTOSTATUSID,
    a.MEDIATYPE AS a_MEDIATYPE,
    a.REACH AS a_REACH,
    a.IMPRESSION AS a_IMPRESSION,
    a.ENGAGEMENT AS a_ENGAGEMENT,
    a.CATEGORYXML AS a_CATEGORYXML,
    a.MEDIAENUM AS a_MEDIAENUM,
    a.LANG AS a_LANG,
    a.LANGUAGENAME AS a_LANGUAGENAME,
    a.POSTTYPE AS a_POSTTYPE,
    a.ISBRANDPOST AS a_ISBRANDPOST,
    a.INSTAGRAMPOSTTYPE AS a_INSTAGRAMPOSTTYPE,
    a.SETTINGID AS a_SETTINGID,
    a.QUOTEDTWEETCOUNTS AS a_QUOTEDTWEETCOUNTS,
    a.INFLUENCERCATEGORY AS a_INFLUENCERCATEGORY,
    a.TYPEOFCOMMENT AS a_TYPEOFCOMMENT,
    a.CATEGORYJSON AS a_CATEGORYJSON,
    a.NLPSENTICONTENT AS a_NLPSENTICONTENT,
    a.ORDERID AS a_ORDERID,
    a.ISHISTORIC AS a_ISHISTORIC,
    a.HASTAGCLOUD AS a_HASTAGCLOUD,
    a.MENTIONMD5 AS a_MENTIONMD5,
    a.CONTENT AS a_CONTENT,
    a.NRESENTIMENTSCORE AS a_NRESENTIMENTSCORE,
    a.CONTEXTUALTAGCLOUD AS a_CONTEXTUALTAGCLOUD,
    a.KEYWORDTAGCLOUD AS a_KEYWORDTAGCLOUD,
    a.EMOJITAGCLOUD AS a_EMOJITAGCLOUD,
    a.AUTHORSOCIALID AS a_AUTHORSOCIALID,
    a.AUTHORNAME AS a_AUTHORNAME,
    a.USERSENTIMENT AS a_USERSENTIMENT,
    a.FOLLOWERSCOUNT AS a_FOLLOWERSCOUNT,
    a.FOLLOWINGCOUNT AS a_FOLLOWINGCOUNT,
    a.TWEETCOUNT AS a_TWEETCOUNT,
    a.USERINFOISVERIFIED AS a_USERINFOISVERIFIED,
    b.BRANDID AS b_BRANDID,
    b.BRANDNAME AS b_BRANDNAME,
    b.CATEGORYGROUPID AS b_CATEGORYGROUPID,
    b.CATEGORYID AS b_CATEGORYID,
    b.CATEGORYNAME AS b_CATEGORYNAME,
    b.CHANNELTYPE AS b_CHANNELTYPE,
    b.CHANNELGROUPID AS b_CHANNELGROUPID,
    b.DESCRIPTION AS b_DESCRIPTION,
    b.SOCIALID AS b_SOCIALID,
    b.OBJECTID AS b_OBJECTID,
    b.NUMLIKESCOUNT AS b_NUMLIKESCOUNT,
    b.NUMCOMMENTS AS b_NUMCOMMENTS,
    b.NUMCOMMENTSCOUNT AS b_NUMCOMMENTSCOUNT,
    b.NUMSHARECOUNT AS b_NUMSHARECOUNT,
    b.NUMVIDEOVIEWS AS b_NUMVIDEOVIEWS,
    b.SHARECOUNT AS b_SHARECOUNT,
    b.CREATEDDATE AS b_CREATEDDATE,
    b.SENTIMENTTYPE AS b_SENTIMENTTYPE,
    b.PASSIVEPOSITIVESENTIMENTCOUNT AS b_PASSIVEPOSITIVESENTIMENTCOUNT,
    b.NEGATIVESENTIMENTCOUNT AS b_NEGATIVESENTIMENTCOUNT,
    b.NEUTRALSENTIMENTCOUNT AS b_NEUTRALSENTIMENTCOUNT,
    b.TAGID AS b_TAGID,
    b.UPPERCATEGORYID AS b_UPPERCATEGORYID,
    b.ISDELETED AS b_ISDELETED,
    b.SIMPLIFIEDTEXT AS b_SIMPLIFIEDTEXT,
    b.RATING AS b_RATING,
    b.ISVERIFIED AS b_ISVERIFIED,
    b.RETWEETEDSTATUSID AS b_RETWEETEDSTATUSID,
    b.INREPLYTOSTATUSID AS b_INREPLYTOSTATUSID,
    b.MEDIATYPE AS b_MEDIATYPE,
    b.REACH AS b_REACH,
    b.IMPRESSION AS b_IMPRESSION,
    b.ENGAGEMENT AS b_ENGAGEMENT,
    b.CATEGORYXML AS b_CATEGORYXML,
    b.MEDIAENUM AS b_MEDIAENUM,
    b.LANG AS b_LANG,
    b.LANGUAGENAME AS b_LANGUAGENAME,
    b.POSTTYPE AS b_POSTTYPE,
    b.ISBRANDPOST AS b_ISBRANDPOST,
    b.INSTAGRAMPOSTTYPE AS b_INSTAGRAMPOSTTYPE,
    b.SETTINGID AS b_SETTINGID,
    b.QUOTEDTWEETCOUNTS AS b_QUOTEDTWEETCOUNTS,
    b.INFLUENCERCATEGORY AS b_INFLUENCERCATEGORY,
    b.TYPEOFCOMMENT AS b_TYPEOFCOMMENT,
    b.CATEGORYJSON AS b_CATEGORYJSON,
    b.NLPSENTICONTENT AS b_NLPSENTICONTENT,
    b.ORDERID AS b_ORDERID,
    b.ISHISTORIC AS b_ISHISTORIC,
    b.HASTAGCLOUD AS b_HASTAGCLOUD,
    b.MENTIONMD5 AS b_MENTIONMD5,
    b.CONTENT AS b_CONTENT,
    b.NRESENTIMENTSCORE AS b_NRESENTIMENTSCORE,
    b.CONTEXTUALTAGCLOUD AS b_CONTEXTUALTAGCLOUD,
    b.KEYWORDTAGCLOUD AS b_KEYWORDTAGCLOUD,
    b.EMOJITAGCLOUD AS b_EMOJITAGCLOUD,
    b.AUTHORSOCIALID AS b_AUTHORSOCIALID,
    b.AUTHORNAME AS b_AUTHORNAME,
    b.USERSENTIMENT AS b_USERSENTIMENT,
    b.FOLLOWERSCOUNT AS b_FOLLOWERSCOUNT,
    b.FOLLOWINGCOUNT AS b_FOLLOWINGCOUNT,
    b.TWEETCOUNT AS b_TWEETCOUNT,
    b.USERINFOISVERIFIED AS b_USERINFOISVERIFIED
FROM
    alert_final_data_stream a
JOIN
    alert_update_data_stream b
WITHIN 24 HOUR
ON
    a.SOCIALID = b.SOCIALID;

"""


# Function to execute ksqlDB query
def execute_ksqldb_query(query):
    response = requests.post(
        f"{KSQLDB_SERVER_URL}/ksql",
        json={"ksql": query}
    )
    if response.status_code == 200:
        print(f"Statement executed successfully: {query}")
        print(response.json())
    else:
        print(f"Failed to execute query: {response.status_code}, {response.text}")


if __name__ == "__main__":
    # Create the mentions_stream_2 stream
    execute_ksqldb_query(create_mentions_stream_query)
